### ISSUE TITLE
Emoji autocomplete: Toot button overlap

### ISSUE THREAD

**Issue by danburzo** [nolanlawson/pinafore#1806]
On iOS Safari 13, the emoji autocomplete list overlaps the Toot button on the main timeline:

![8750B069-25E2-4EE6-A9AA-17E0B33CE7E5](https://user-images.githubusercontent.com/205375/86039583-4cade600-ba4b-11ea-9506-cbaf8789c247.png)

**Comment by danburzo** [comment]
This also reproduces in macOS Safari. It seems to be a discrepancy in stacking contexts, but I need to dig in to figure out exactly what causes it.

**Comment by danburzo** [comment]
Okay this one was a bit of a doozy, but with [some debug code](https://gist.github.com/danburzo/e9c495ae2860161966d7800ee3203695) I traced it down to: `.main-content { contain: content } `. In browsers which understand `contain` it creates a stacking context, trapping the _Toot_ button underneath the autocomplete list regardless of either's z-index. Safari, which does not support `contain`, does not, so the button's 5000 z-index trumps the autocomplete's value of 90. 

I imagine the least risky fix, at this point (although it may have unintended consequences of its own?), is to bump the autocomplete list's z-index to 5000+.

**Comment by danburzo** [comment]
On second thought, this sounds like a better solution:

```css
.main-content {
  contain: content; // see https://www.w3.org/TR/2018/CR-css-contain-1-20181108/#valdef-contain-content
  padding-top: var(--main-content-pad-top);
}

/* 
  For browsers which don't support the "contain" CSS property,
  make a stacking context manually so that the z-index behavior
  is consistent. See: https://github.com/nolanlawson/pinafore/issues/1806
*/
@supports not (contain: content) {
  .main-content {
    isolation: isolate;
  }
}
```
